### ISSUE TITLE
Acces to external users ?

### ISSUE THREAD

**Issue by LauLauThom** [boguss1225/ObjectDetectionGUI#1]
Hi,
Your project looks interesting, however the link to download the exe is not available, and as far as I understood the tool is only limited to people member of the Tasmanian university, which highly limits the distribution of the tool.

Is it so that it is more of a proof of concept project or do you have plans to somehow allow external users ?

**Comment by boguss1225** [comment]
Hi
Thank you for having interest of this project.
As you mentioned, this project is designed for internal and exclusive group since most of deep learning data and hardware resources are needed to be kept private. This project is more focused on implementing GUI for beginner level user. You can utilize this git repository to implement both server side and client side. After then you can generate exe file for distribution for users.

If you need help, I can help you to implement and generate exe file in your system. Theoretically, this GUI can allows unlimited number of users as long as hardware resources are allowed.

Thanks
Best regards 
Boguss

**Comment by LauLauThom** [comment]
Thanks for the reply, I work as a data scientist so I don't really have interest having a server/client system to be honest, I mostly work with local resources so I think compiling everything would be too much efforts for me.
Thanks for the tips though, I will keep it in mind.
